Settings:
  Prefix: '&8[&aCrazyEnchants&8&l]>> &r' #自定义插件消息前缀
  InvName: '&4&l&n疯狂附魔台' #The name of the /CE inventory
  Enchantment-Book-Item: '340' #The item that the enchantment book is.
  Enchantment-Book-Glowing: true #Toggle on or off if the book will have an enchanted look.
  GUISize: 54 #The size of the GUI, must be a factor of 9
  Clouds: true #Enable and Disable the Clouds for the Wings Enchantment
  EnchantmentBookLore: #The lore on the enchantments books.
    - '&7拖动一本书和一个东西.'
    - '&7右击获得更多信息.'
    - '%Description%'
    - '&4%Destroy_Rate%% 损坏概率
    - '&a%Success_Rate%% 成功概率'
  LostBook: #Lost book options.
    Item: '340' #The item the lost books is.
    Name: '&8&l&n一本损毁的 %Category%&8&l&n 书' #The name of the lost books.
    Lore: #The lore of the lost books.
      - '&7这本书被遗失了几个世纪'
      - '&7依稀还能辨认是属于 %Category% &7品级的附魔书.'
      - '&7你可以把它清理干净看出它具体的属性.'
      - '&7&l(&6&l!&7&l) &7右击清理.'
  Scrambler:
    Item: '175' #The item it will be.
    Glowing: true #If it has the glowing effect.
    Name: '&e&l附魔随机器' #The name of the item.
    Lore: #The lore of the item.
      - '&7The &e&l附魔随机器 &7可以让你'
      - '&7重新随机你的物品的损毁率和成功率.'
      - '&7把它和附魔书混到一起'
      - '&7获得一个新的损毁率和成功等级.'
    GUI: #Options for the GUI.
      Name: '&8洗点' #Name of the GUI.
      Toggle: true #If the GUI will show. Warning>> This may cause lag if a lot of players are using it all the time.
      Pointer: #The pointer in the middle of the GUI.
        Item: '76' #The item the pointer is.
        Name: '&c&l指示器' #The name of the pointer.
        Lore: #The lore on the pointer.
          - '&7不管现有的是什么'
          - '&7新的概率都是随机的.'
    InGUI: false #If you can buy it in the GUI.
    Slot: 1 #The slot the item will be in.
    GUIName: '&e&l附魔随机器' #Name of the item in the GUI.
    GUILore: #The lore of the item in the GUI.
      - '&7The &e&l附魔随机器 &7可以让你'
      - '&7重新随机你的物品的损毁率和成功率.'
      - '&7把它和附魔书混到一起'
      - '&7获得一个新的损毁率和成功等级.'
      - ''
      - '&e花费: &e&l$800'
  GKitz: #GKitz GUI option.
    InGUI: false #If you can open the GKitz GUI from the main /ce gui.
    Slot: 1 #The slot it will be in.
    Item: '311' #The item it is.
    Glowing: true #If the item has a glowing effect.
    Name: '&c&lGKit' #The name of the item.
    Lore: #The lore of the item.
      - '&b>>&7&n点击打开&b<<'
  ProtectionCrystal:
    InGUI: false #If its in the GUI.
    Slot: 1 #Slot it is in
    Item: '388' #Item it is
    Glowing: true #If it is enchanted
    Protected: '&6垣古加护' #The lore that goes on the item that is protected.
    Chance: #The option to allow the protection to fail.
      Toggle: false #Toggle if the protection has a chance of failing.
      Success-Chance: 75 #The chance that the protection will work.
    Name: '&5&l保护&b&l水晶' #Name of the item
    Lore: #Lore of the item
      - '&7稀有的水晶'
      - '&7保护物品不会消失'
      - '&7保用一生.'
      - ''
      - '&7&l(&6&l!&7&l) &7和一个物品放在一起.'
    GUIName: '&5&lProtection &b&lCrystal'
    GUILore:
      - '&7稀有的水晶'
      - '&7保护物品不会消失'
      - '&7保用一生.'
      - ''
      - '&e花费: &e&l$500'
  BlackSmith: #Options for the Black Smith
    InGUI: true #In the GUI.
    Slot: 24 #Slot it is in.
    Item: '145' #Item that shows in the GUI
    Glowing: false #Is it enchanted
    Name: '&7&l铁匠' #Name of the Item in the GUI
    Lore: #Lore on the item.
      - '&b>>&7&n点击打开&b<<'
    GUIName: '&8&l铁匠' #Name of the Black Smith's GUI
    Results:
      None: '&c&l没有结果' #Name of the item when there are no results in the Black Smith
      Not-Found-Lore:
        - '&7没有找到结果.'
        - '&7请放置两个'
        - '&7附魔和等级一样的附魔书.'
        - '&7或放两样东西,'
        - '&7合并它们的附魔.'
      Found: '&c&花费: &6&l%Cost%经验' #The lore at the bottom of the item
    Transaction: #Options for the pricing
      Currency: XP_Level
      Costs: #Cost options
        Power-Up: 5 #When a enchantment levels up 1 on an item
        Add-Enchantment: 3 #When it adds an enchantment to the item from another item
        Book-Upgrade: 5 #Leveling up a books power
  Tinker: #Settings for Info item in the GUI
    InGUI: true #Toggle whether it is in the /CE GUI or not
    Slot: 22 #Slot it is in
    Item: '399' #Item it is
    Glowing: false #Whether it glows like its enchanted
    Name: '&7&l疯狂附魔师' #Name of the Item
    Lore: #Lore of the item
      - '&b>>&7&n点击打开&b<<'
  Info: #Settings for Info item in the GUI
    InGUI: true #Toggle whether it is in the /CE GUI or not
    Slot: 23 #Slot it is in
    Item: '345' #Item it is
    Glowing: true #Whether it glows like its enchanted
    Name: '&e附魔信息' #Name of the Item
    Lore: #Lore of the item
      - '&b>>&7&n点击查看&b<<'
  Dust: #Settings for the Magical Dust
    MysteryDust:
      Item: '289' #Item mystery dust is
      Name: '&7Mystery Dust' #Name of the dust
      Lore: #Use %Percent% to set the percent
        - '&a1-%Percent%% &7will be on a'#然而并看不懂
        - '&aMagical AngelDust &7or &eMagical Fixing &7Dust'
        - '&7&l(&6&l!&7&l) &7Right click'
      Firework:
        Toggle: true #Toggle if the firework happens on open.
        Colors: 'Black, Gray, Lime' #The colors the firework will be.
      Dust-Toggle:
        Success: true #Toggle whether you can get success dust from Mystery Dust.
        Destroy: true #Toggle whether you can get destroy dust from Mystery Dust.
        Failed: true #Toggle whether you can get failed dust from Mystery Dust.
      PercentRange: #Range the mystery rate will be.
        Max: 30 #Max percent
        #Min will always be 1.
    SuccessDust:
      InGUI: true #If you can buy it in the /CE GUI
      GUIName: '&a魔力天使之尘' #Name of the item in the GUI
      GUILore: #Lore in the GUI.
        - '&e花费: &a&l$500'
        - '&7可以使你提升&aSuccess Rate&7的尘土.'
      Slot: 25 #Slot number it is in
      Item: '353' #Item the dust is
      Name: '&a魔法天使尘土' #Name of the dust
      Lore: #Lore for the dust
        - '&a+%Percent%% 成功概率'
        - '&7可以使附魔书'
        - '&7提高 &e%Percent%% &7的成功率.'
      PercentRange: #Range the success rate will be.
        Max: 30 #Max percent
        Min: 2 #Minimum percent
    DestroyDust:
      InGUI: true #If you can buy it in the /CE GUI
      GUIName: '&e魔力修复之尘' #Name of the item in the GUI
      GUILore: #Lore in the GUI.
        - '&e花费: &a&l$500'
        - '&7可以使你降低&4损毁率&7的尘土.'
      Slot: 34 #Slot number it is in
      Item: '331' #Item the dust is
      Name: '&e魔力修复之尘' #Name of the dust
      Lore: #Lore for the dust
        - '&c-%Percent%% 损毁率'
        - '&7允许附魔书降低自身 &e%Percent% 的损毁率.'
      PercentRange: #Range the destroy rate will be.
        Max: 10 #Max percent
        Min: 2 #Minimum percent
    FailedDust:
      Item: '289' #Item the dust is
      Name: '&7失败之尘' #Name of the dust
      Lore: #Lore for the dust
        - '&7这个尘土失去了它的作用.'
        - '&7这个尘土在魔法层面上对你没有用了.'
        - '&7可以用它来做投掷药水或TNT.'
  BlackScroll: #Settings for the black scrolls
    Item: '351' #The item the black scroll can be
    Name: '&8&l&n黑卷轴' #The name of the black scroll
    Item-Lore: #The lore that will be on the black scroll.
      - '&7有一个你不想要的附魔?'
      - '&7把这个物品和想带走附魔的物品放在一起'
      - '&7它会帮你带走一个随机的附魔.'
      - '&7&l(&6&l!&7&l) &7只对自定义附魔生效.'
    Chance-Toggle: false #Toggle on and off if the black scrolls have a chance of failing.
    Chance: 75 #The chance that the black scroll will work.
    InGUI: true #Toggle being able to buy in the /CE GUI. Cost is controlled in the SignOptions section
    GUIName: '&7黑卷轴'
    Glowing: false #If the item is glowing.
    Slot: 21 #Slot you can buy the scroll at
    Lore: #Lore of the item in the GUI
      - '&e花费: &a&l$1000'
      - '&7黑卷轴允许你带走一个随机的附魔.'
    SuccessChance: #Controls what the success chance will be when they get the book from the Black Scroll
      Max: 75 #The Max percent
      Min: 35 #The Minimum percent
    DestroyChance: #Controls what the destroy chance will be when they get the book from the Black Scroll
      Max: 25 #The Max percent
      Min: 5 #The Minimum percent
  WhiteScroll:
    Item: '339' #The item the white scroll is.
    Name: '&e&l白卷轴' #The name of the white scrolls.
    Item-Lore: #The lore that will be on the white scroll.
      - '&7想要保护一个损坏率很高的物品?'
      - '&7把这个物品和想要附魔的物品放在一起'
      - '&7然后它会保护你的东西不被损坏.'
    InGUI: true #Toggle being able to buy in the /CE GUI. Cost is controlled in the SignOptions section
    GUIName: '&7白卷轴'
    Glowing: true #If the item is glowing.
    Slot: 30 #Slot you can buy the scroll at
    Lore: #Lore of the scroll in the GUI
      - '&e花费: &a&l$2000'
      - '&7白卷轴允许你保护一个东西不被损坏.'
    ProtectedName: '&b&l被保护的' #The lore that is added to protect an item.
  TransmogScroll:
    Item: '406' #The item the scroll is.
    Name: '&d&lTransmog Scroll' #The name of the scroll.
    Item-Lore: #The lore that will be on the scroll.
      - '&7This scroll allows you to organize'
      - '&7your enchantments and tell you how many'
      - '&7enchantments you currently have on the item.'
    InGUI: false #Toggle being able to buy in the /CE GUI. Cost is controlled in the SignOptions section
    GUIName: '&dTransmog Scroll'
    Glowing: false #If the item is glowing.
    Slot: 30 #Slot you can buy the scroll at
    Lore: #Lore of the scroll in the GUI
      - '&e花费: &a&l$200'
      - '&7This scroll allows you to organize'
      - '&7your enchantments and tell you how many'
      - '&7enchantments you currently have on the item.'
    Amount-of-Enchantments: ' &7[&6&n%Amount%&7]' #The suffix that will be added at the end of the item's name.
    Amount-Toggle: true #If the amount is added to the suffix of the item's name.
    Count-Vanilla-Enchantments: true #If it counts the vanilla enchantments in the amount.
  EnchantmentOptions: #Options for enchanted books.
    MaxAmountOfEnchantmentsToggle: true #Turn on an off the Max amount of enchantments. Use crazyenchantments.limit.# permission to set the limit.
    IncludeVanillaEnchantments: false #Count Vanilla enchantments also?
    MaxRageLevel: 4 #The max amount rage can stack when fighting.
    Right-Click-Book-Description: true #Toggles whether when you right click the enchantment book if it messages the player the description or not.
    UnSafe-Enchantments: true #Having this set to true will allow players to use enchantments levels above the max level.
    Armor-Upgrade: #Having this enabled will allow players to try and add a higher level of an enchantment onto an item with a lower level of the enchantment.
      Toggle: true #Toggle on or off the ability to upgrade the enchantments.
      Enchantment-Break: true #If the book's destroy rate happens the item doesn't break but instead the current lower version of the enchantment is destroyed. If false then the item will be destroyed instead.
    Wings: #Options for the Wings Enchantment.
      Enemy-Toggle: true #This toggles on and off the wings enchantment when an enemy is # away from the player.
      Distance: 25 #How far away the enemy has to be to toggle off the enchantment.
      Regions: #All world guard regions the Wings enchantment can work in.
        - 'Free_Fly'
        - 'SafeZone'
  Costs: #This is where you set the cost of stuff in the shop GUI. https://github.com/kicjow/Crazy-Enchantments/wiki/Currency-Types
    Scrambler: #The item that is being bought.
      Cost: 800 #How much the item will cost.
      Currency: Vault #The currency that will be taken when bought.
    ProtectionCrystal:
      Cost: 500
      Currency: Vault
    TransmogScroll:
      Cost: 200
      Currency: Vault
    BlackScroll:
      Cost: 1000
      Currency: Vault
    WhiteScroll:
      Cost: 2000
      Currency: Vault
    SuccessDust:
      Cost: 500
      Currency: Vault
    DestroyDust:
      Cost: 500
      Currency: Vault
  SignOptions: #Options for the Signs.
    CategoryShopStyle: #What the sign will look like. The price will be determined by the category you pick
      Line1: '&b&l疯狂附魔' #Line 1 of the sign
      Line2: '&b&lShop:' #Line 2 of the sign
      Line3: '&2&l%Category%' #Line 3 of the sign
      Line4: '&c&l花费: &6&l%Cost%XP' #Line 4 of the sign
      Buy-Message: '&7You have just bought an enchantment book, and it is %BookName%&7 from the %Category%&7 tier.'
    ProtectionCrystalStyle: 
      Line1: '&b&l疯狂附魔'
      Line2: '&b&lShop:'
      Line3: '&5&lProtection &b&lCrystal'
      Line4: '&c&l花费: &a&l$500'
      Buy-Message: '&7You have just bought a &5&lProtection &b&lCrystal.' #Message when buying an item.
    ScramblerStyle: 
      Line1: '&b&l疯狂附魔'
      Line2: '&b&lShop:'
      Line3: '&e&lScrambler'
      Line4: '&c&l花费: &a&l$800'
      Buy-Message: '&7You have just bought a &e&lThe Grand Scrambler&7.' #Message when buying an item.
    SuccessDustStyle: 
      Line1: '&b&l疯狂附魔'
      Line2: '&b&lShop:'
      Line3: '&e&lMagical Angel Dust'
      Line4: '&c&l花费: &a&l$500'
      Buy-Message: '&7You have just bought a &aMagical Angel Dust&7.'
    DestroyDustStyle: 
      Line1: '&b&l疯狂附魔'
      Line2: '&b&lShop:'
      Line3: '&e&lMagical Fixing Dust'
      Line4: '&c&l花费: &a&l$500'
      Buy-Message: '&7You have just bought a &eMagical Fixing Dust&7.'
    BlackScrollStyle: 
      Line1: '&b&l疯狂附魔'
      Line2: '&b&lShop:'
      Line3: '&4&lBlack &8&lScrolls'
      Line4: '&c&l花费: &a&l$1000'
      Buy-Message: '&7You have just bought a &8&l&nBlack Scroll&7.'
    WhiteScrollStyle:
      Line1: '&b&l疯狂附魔'
      Line2: '&b&lShop:'
      Line3: '&f&lWhite &b&lScrolls'
      Line4: '&c&l花费: &a&l$2000'
      Buy-Message: '&7You have just bought a &e&lWhite Scroll&7.'
    TransmogScrollStyle:
      Line1: '&b&l疯狂附魔'
      Line2: '&b&lShop:'
      Line3: '&d&lTransmog &b&lScrolls'
      Line4: '&c&l花费: &a&l$200'
      Buy-Message: '&7You have just bought a &d&lTransmog Scroll&7.'
  GUICustomization: #This allows you to customize unclickable items into you GUI.
    - 'Slot:1, Item:160:15, Name: '
    - 'Slot:2, Item:160:15, Name: '
    - 'Slot:3, Item:160:15, Name: '
    - 'Slot:4, Item:160:15, Name: '
    - 'Slot:5, Item:160:15, Name: '
    - 'Slot:6, Item:160:15, Name: '
    - 'Slot:7, Item:160:15, Name: '
    - 'Slot:8, Item:160:15, Name: '
    - 'Slot:9, Item:160:15, Name: '
    - 'Slot:10, Item:160:15, Name: '
    - 'Slot:18, Item:160:15, Name: '
    - 'Slot:19, Item:160:15, Name: '
    - 'Slot:27, Item:160:15, Name: '
    - 'Slot:28, Item:160:15, Name: '
    - 'Slot:36, Item:160:15, Name: '
    - 'Slot:37, Item:160:15, Name: '
    - 'Slot:45, Item:160:15, Name: '
    - 'Slot:46, Item:160:15, Name: '
    - 'Slot:47, Item:160:15, Name: '
    - 'Slot:48, Item:160:15, Name: '
    - 'Slot:49, Item:160:15, Name: '
    - 'Slot:50, Item:160:15, Name: '
    - 'Slot:51, Item:160:15, Name: '
    - 'Slot:52, Item:160:15, Name: '
    - 'Slot:53, Item:160:15, Name: '
    - 'Slot:54, Item:160:15, Name: '
    - 'Slot:11, Item:160:0, Name: '
    - 'Slot:12, Item:160:0, Name: '
    - 'Slot:13, Item:160:0, Name: '
    - 'Slot:14, Item:160:0, Name: '
    - 'Slot:15, Item:160:0, Name: '
    - 'Slot:16, Item:160:0, Name: '
    - 'Slot:17, Item:160:0, Name: '
    - 'Slot:20, Item:160:0, Name: '
    - 'Slot:26, Item:160:0, Name: '
    - 'Slot:29, Item:160:0, Name: '
    - 'Slot:35, Item:160:0, Name: '
    - 'Slot:38, Item:160:0, Name: '
    - 'Slot:39, Item:160:0, Name: '
    - 'Slot:40, Item:160:0, Name: '
    - 'Slot:41, Item:160:0, Name: '
    - 'Slot:42, Item:160:0, Name: '
    - 'Slot:43, Item:160:0, Name: '
    - 'Slot:44, Item:160:0, Name: '
Categories: #You can make as many different categories as you want
  Common: #Name of the category
    Name: '&a&l&nCommon' #Name in the GUI
    Slot: 31 #The Slot number the item will be in
    InGUI: true #Toggle if its in the GUI or not.
    Lore: #The lore of the Item
      - '&e花费: &6&l20 &6XP Levels'
    Item: '160:5' #The id for the item
    Cost: 20 #How much each book will cost to buy.
    Currency: XP_Level #The currency you wish to use. https://github.com/kicjow/Crazy-Enchantments/wiki/Currency-Types
    Rarity: 1 #This allows the enchantments to be ordered with the Transmog Scrolls. The higher the number the more rare it is. Try and have each category have different rarities.
    LostBook: #Controls the Lost Book shop for this tier
      InGUI: false #If it shows in the /CE Gui
      Slot: 1 #Slot it will be in
      Item: '340' #The item that is shown in the GUI
      Glowing: false #Is it enchanted
      Name: '&8&l&nLost&c&l Tier1 &8&l&nBooks' #Name of the item
      Lore: #Lore on the item
        - '&7These are lost books that are'
        - '&7Said to be &c&lTier1 &7Enchantment books.'
        - '&7But no one has tried to clean the books yet.'
        - '&7Will you be the one to clean the books?'
        - ''
        - '&c&l花费: &6&l$1000'
      Cost: 1000
      Currency: Vault
      FireworkToggle: true #Toggle on and off if when opening a lost book a firework effect happens
      FireworkColors: 'Red, White, Blue' #The colors of the firework
    EnchOptions: #Enchantment Options
      SuccessPercent: #The range for the success rate that the enchantment will have
        Max: 90 #The max success rate
        Min: 40 #The min success rate
      DestroyPercent: #The range for the destroy rate that the enchantment will have
        Max: 10 #The max destroy rate
        Min: 0 #The min destroy rate
      MaxLvlToggle: true #Turn on and off Max Level cap
      LvlRange: #The range of lvls that can be found in the Category.
        Max: 2
        Min: 1
  Rare:
    Name: '&9&l&nRare'
    Slot: 32
    InGUI: true
    Lore:
      - '&e花费: &6&l40 &6XP Levels'
    Item: '160:11'
    Cost: 40
    Currency: XP_Level
    Rarity: 2
    LostBook:
      InGUI: false
      Slot: 2
      Item: '340'
      Glowing: false
      Name: '&8&l&nLost&c&l Tier2 &8&l&nBooks'
      Lore:
        - '&7These are lost books that are'
        - '&7Said to be &c&lTier2 &7Enchantment books.'
        - '&7But no one has tried to clean the books yet.'
        - '&7Will you be the one to clean the books?'
        - ''
        - '&c&l花费: &6&l$2000'
      Cost: 2000
      Currency: Vault
      FireworkToggle: true
      FireworkColors: 'Black, Yellow'
    EnchOptions:
      SuccessPercent:
        Max: 70
        Min: 35
      DestroyPercent:
        Max: 25
        Min: 10
      MaxLvlToggle: true
      LvlRange:
        Max: 3
        Min: 2
  Legendary:
    Name: '&4&l&nLegendary'
    Slot: 33
    InGUI: true
    Lore:
      - '&e花费: &6&l60 &6XP Levels'
    Item: '160:14'
    Cost: 60
    Currency: XP_Level
    Rarity: 3
    LostBook:
      InGUI: false
      Slot: 3
      Item: '340'
      Glowing: false
      Name: '&8&l&nLost&c&l Tier3 &8&l&nBooks'
      Lore:
        - '&7These are lost books that are'
        - '&7Said to be &c&lTier3 &7Enchantment books.'
        - '&7But no one has tried to clean the books yet.'
        - '&7Will you be the one to clean the books?'
        - ''
        - '&c&l花费: &6&l$3000'
      Cost: 3000
      Currency: Vault
      FireworkToggle: true
      FireworkColors: 'White, Gray'
    EnchOptions:
      SuccessPercent:
        Max: 50
        Min: 25
      DestroyPercent:
        Max: 35
        Min: 15
      MaxLvlToggle: true
      LvlRange:
        Max: 5
        Min: 3